version: 2

sources:
  
  - name: jaffle_shop
    description: clone of a postgres application database
    schema: jaffle_shop
    database: raw
    loaded_at_field: _etl_loaded_at
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: customers
        description: raw customer data
        freshness: null
        columns:
          - name: id
            description: primary key for customers data
            tests:
              - unique
              - not_null

      - name: orders
        description: raw orders data
        columns:
          - name: id
            tests:
              - unique
              - not_null

  - name: jaffle_shop_stripe
    schema: stripe
    database: raw
    loaded_at_field: _etl_loaded_at
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: payment
